server:
  port: 8762
  servlet:
    context-path: /eureka-provider

spring:
  application:
    name: eureka-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/