eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8764
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer-demo

# feign自带断路器，需要开启
feign:
  hystrix:
    enabled: true